entero contador, edad, contador_mayor
inicio
	contador <-1
	contador_mayor <- 0
	mientras contador <= 10 haga
		escriba "DE EDAD # ", contador, " "
		lea edad
		si edad >= 18 entonces
			contador_mayor <- contador_mayor + 1
			
		fin si
		llamar nueva_linea
		
		
		contador <- contador + 1
		fin mientras
		escriba "MAYORES DE EDAD SON ", contador_mayor
		llamar nueva_linea
		escriba "FIN DE CICLO "
fin
